name: Daily Temperature Collection & Tweet

on:
  schedule:
    - cron: '30 12 * * *'  # Runs at 12:30 PM UTC (6:00 PM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Collect Weather Data
        env:
          VISUALCROSSINGAPI: ${{ secrets.VISUALCROSSINGAPI }}
        run: python dataupdation.py

      - name: Commit and Push Changes (if data is updated)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Stash local changes to prevent merge conflicts
          git stash --include-untracked

          # Pull latest changes
          git pull origin main --rebase

          # Reapply stashed changes
          git stash pop || echo "No local changes to reapply"

          # Add and commit JSON updates
          git add "*.json"
          git commit -m "Update weather data [GitHub Actions]" || echo "No changes to commit"
          git push origin main

  tweet-temperature:
    runs-on: ubuntu-latest
    needs: collect-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Tweet Temperature
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweeting.py
